services:
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: guild-scheduler
    user: root
    privileged: true
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  guild-ui:
    build: .
    container_name: hypixel-ui
    command: streamlit run search_ui.py --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    restart: always
    environment:
      - DB_NAME=/app/data/guild_data.db

  guild-tracker:
    build: .
    container_name: hypixel-tracker
    volumes:
      - ./data:/app/data
    environment:
      - HYPIXEL_API_KEY=${HYPIXEL_API_KEY}
      - DB_NAME=/app/data/guild_data.db
    command: python guild_stats.py
    restart: "no"
    labels:
      ofelia.enabled: "true"
      ofelia.job-run.guild-pull.schedule: "@daily"
